hook.Add("ArcCW_LocalizationLoaded", "ArcCW_CS+", function()
    local addlang = {
        ["en"] = {
            ["pro.ignite"] = "Ignites targets",
            ["pro.ammo_blank"] = "Harmless!",
            ["con.ammo_blank"] = "Harmless.",
            ["pro.ammo_ricochet"] = "Bullets bounce off surfaces",
            ["pro.rpg.splash"] = "+ Splash damage",
            ["con.rpg.splash"] = "- Splash damage",
            ["pro.rpg.damage"] = "+ Direct damage",
            ["con.rpg.damage"] = "- Direct damage",
            ["pro.rpg.smoke"] = "Creates smokescreen",
            ["con.rpg.smoke"] = "- Damage",
            ["con.projectilecount"] = "- Projectile count",
            ["con.projectilecount"] = "- Projectile count",
            ["pro.fcg_accelerator"] = "Up to 25% faster fire rate",
            ["con.fcg_accelerator"] = "Fire rate starts slower",
            ["pro.auto"] = "Full automatic fire",
            ["pro.burst"] = "Burst-fire mode",
            ["con.burstdelay"] = "Brief burst delay",
            ["pro.hyper"] = "Hyper-burst mode",
            ["pro.hyper2"] = "Insane rate of fire",
            ["con.burstdelay2"] = "Slow burst delay",
            ["pro.regulator"] = "Automatic fire with adjustable rate",
            ["con.regulator"] = "Maximum 80% fire rate",
            ["con.semi"] = "Semi-automatic fire only",
            ["pro.sputter"] = "Sputter mode",
            ["con.sputter"] = "Fires until magazine is empty",
            ["con.sputter2"] = "No safety and semi-auto",
            ["con.beam"] = "Visible laser beam",
            ["pro.muzz_circlechoke"] = "Circle pattern",
            ["con.muzz_circlechoke"] = "Pellets literally go around your point of aim",
            ["pro.muzz_crosschoke"] = "Cross pattern",
            ["con.situational"] = "Situational",
            ["pro.muzz_duckbill"] = "Produces short, wide spread",
            ["con.muzz_duckbill"] = "Poor at hitting single targets",
            ["pro.flashhiding"] = "Hides muzzle flash",
            ["con.perk_last"] = "One round only",
            ["pro.perk_owyn"] = "+ Damage on last round",
            ["info.perk_owyn"] = "Damage bonus at maximum with 60 round capacity",
            ["con.obstruction"] = "May obstruct sights",
            ["pro.ubgl"] = "Selectable underbarrel launcher",
            ["pro.ubsg"] = "Selectable underbarrel shotgun",
            ["pro.pistol_onehand"] = "Shoot while sprinting",
            ["pro.perk_underwater"] = "Shoot underwater",
        }
    }
    table.Merge(ArcCW.LangTable, addlang)
end)